const now = () => new Date().toISOString();
const daysFromNow = (days) => new Date(Date.now() + days * 86400000).toISOString();

export const demoSeedPhases = [
  {
    key: "phase1_core",
    title: "Phase 1 Core Operations",
    description: "Seeds customers, drivers, fleet, finance partner, and an assigned load so dashboard, CRM, fleet, finance, and driver pages have visible data.",
    records: {
      Client: [
        {
          id: "demo-client-valor",
          company_name: "Valor Manufacturing",
          contact_name: "Alicia Parker",
          customer_type: "shipper",
          contact_email: "demo-customer@example.com",
          phone: "910-555-0144",
          city: "Fayetteville",
          state: "NC",
          status: "active",
        },
        {
          id: "demo-client-apex",
          company_name: "Apex Freight Brokers",
          contact_name: "Marcus Allen",
          customer_type: "broker",
          contact_email: "demo-broker@example.com",
          phone: "704-555-0180",
          city: "Charlotte",
          state: "NC",
          status: "active",
        },
      ],
      Driver: [
        {
          id: "demo-driver-sprinter",
          user_id: "local-driver-user",
          full_name: "Demo Driver",
          vehicle_type: "Sprinter",
          max_payload: 3000,
          availability: "available",
          status: "available",
          compliance_status: "valid",
          home_city: "Fayetteville",
          home_state: "NC",
          phone: "910-555-0120",
        },
        {
          id: "demo-driver-hotshot",
          full_name: "Carlos Ramirez",
          vehicle_type: "Hot Shot",
          max_payload: 12000,
          availability: "available",
          status: "available",
          compliance_status: "valid",
          home_city: "Charlotte",
          home_state: "NC",
          phone: "704-555-0191",
        },
        {
          id: "demo-driver-dryvan",
          full_name: "Nina Thompson",
          vehicle_type: "Dry Van",
          max_payload: 44000,
          availability: "available",
          status: "available",
          compliance_status: "valid",
          home_city: "Greensboro",
          home_state: "NC",
          phone: "336-555-0177",
        },
      ],
      Truck: [
        {
          id: "demo-truck-sprinter",
          truck_number: "HV-SPR-01",
          vehicle_type: "Sprinter",
          driver_id: "demo-driver-sprinter",
          status: "active",
          vin: "DEMO-SPRINTER-001",
          license_plate: "NC-SPR01",
        },
        {
          id: "demo-truck-hotshot",
          truck_number: "HV-HOT-02",
          vehicle_type: "Hot Shot",
          driver_id: "demo-driver-hotshot",
          status: "active",
          vin: "DEMO-HOTSHOT-002",
          license_plate: "NC-HOT02",
        },
      ],
      FactoringCompany: [
        {
          id: "demo-factor-fastpay",
          name: "FastPay Demo Factoring",
          company_name: "FastPay Demo Factoring",
          status: "active",
          fee_percent: 2.5,
          payment_terms: "Same day after invoice approval",
          contact_email: "demo-factoring@example.com",
        },
      ],
      Load: [
        {
          id: "demo-load-assigned-001",
          load_number: "HST-ASSIGNED-001",
          status: "assigned",
          driver_id: "local-driver-user",
          broker_id: "demo-client-apex",
          origin_city: "Fayetteville",
          origin_state: "NC",
          origin_zip: "28301",
          destination_city: "Raleigh",
          destination_state: "NC",
          destination_zip: "27601",
          equipment_type: "Sprinter",
          commodity: "Medical supplies",
          weight: 1500,
          miles: 68,
          rate: 700,
          total_revenue: 700,
          pickup_date: daysFromNow(1),
          delivery_date: daysFromNow(1),
        },
      ],
      Document: [
        {
          id: "demo-doc-coi",
          title: "Demo Certificate of Insurance",
          document_type: "insurance",
          status: "approved",
          driver_id: "demo-driver-sprinter",
          expires_at: daysFromNow(45),
        },
      ],
    },
  },
  {
    key: "phase2_marketplace",
    title: "Phase 2 Marketplace + Auction",
    description: "Seeds external marketplace loads and driver bid records so dispatch can test Match, Auction, Bid Review, and driver Offers.",
    records: {
      ExternalLoad: [
        {
          id: "demo-ext-sprinter-001",
          source_provider: "DAT Demo",
          external_load_id: "DAT-SPR-001",
          broker_name: "Apex Freight Brokers",
          broker_customer_id: "demo-client-apex",
          pickup_city: "Fayetteville",
          pickup_state: "NC",
          pickup_zip: "28301",
          delivery_city: "Raleigh",
          delivery_state: "NC",
          delivery_zip: "27601",
          required_equipment: "Sprinter",
          weight: 1800,
          miles_total: 68,
          rate_available: 650,
          commodity: "Auto parts",
          normalized_status: "available",
          imported_at: now(),
          expires_at: daysFromNow(1),
        },
        {
          id: "demo-ext-hotshot-002",
          source_provider: "Truckstop Demo",
          external_load_id: "TS-HOT-002",
          broker_name: "Apex Freight Brokers",
          broker_customer_id: "demo-client-apex",
          pickup_city: "Charlotte",
          pickup_state: "NC",
          pickup_zip: "28202",
          delivery_city: "Atlanta",
          delivery_state: "GA",
          delivery_zip: "30301",
          required_equipment: "Hot Shot",
          weight: 9200,
          miles_total: 245,
          rate_available: 1750,
          commodity: "Machinery parts",
          normalized_status: "auction",
          imported_at: now(),
        },
        {
          id: "demo-ext-dryvan-003",
          source_provider: "123Loadboard Demo",
          external_load_id: "123-DV-003",
          broker_name: "Valor Manufacturing",
          broker_customer_id: "demo-client-valor",
          pickup_city: "Greensboro",
          pickup_state: "NC",
          pickup_zip: "27401",
          delivery_city: "Richmond",
          delivery_state: "VA",
          delivery_zip: "23219",
          required_equipment: "Dry Van",
          weight: 22000,
          miles_total: 205,
          rate_available: 1400,
          commodity: "Retail freight",
          normalized_status: "available",
          imported_at: now(),
        },
      ],
      DriverLoadBid: [
        {
          id: "demo-bid-hotshot-001",
          external_load_id: "demo-ext-hotshot-002",
          driver_id: "demo-driver-hotshot",
          status: "interested",
          match_score: 94,
          driver_notes: "Available today after 2 PM.",
          submitted_at: now(),
        },
        {
          id: "demo-bid-sprinter-001",
          external_load_id: "demo-ext-sprinter-001",
          driver_id: "local-driver-user",
          status: "bid_submitted",
          match_score: 96,
          driver_bid_amount: 500,
          driver_notes: "Can pick up within 60 minutes.",
          submitted_at: now(),
        },
      ],
    },
  },
  {
    key: "phase2c_protection",
    title: "Phase 2C Protection Test Data",
    description: "Seeds a duplicate-bid scenario and an already-assigned external load so duplicate prevention and accepted-bid lockout can be verified.",
    records: {
      ExternalLoad: [
        {
          id: "demo-ext-lockout-004",
          source_provider: "DAT Demo",
          external_load_id: "DAT-LOCK-004",
          broker_name: "Valor Manufacturing",
          broker_customer_id: "demo-client-valor",
          pickup_city: "Durham",
          pickup_state: "NC",
          delivery_city: "Norfolk",
          delivery_state: "VA",
          required_equipment: "Sprinter",
          weight: 2100,
          miles_total: 190,
          rate_available: 950,
          commodity: "Electronics",
          normalized_status: "imported",
          imported_load_id: "demo-load-lockout-004",
          assigned_driver_id: "local-driver-user",
          imported_at: now(),
        },
      ],
      DriverLoadBid: [
        {
          id: "demo-bid-duplicate-001",
          external_load_id: "demo-ext-sprinter-001",
          driver_id: "local-driver-user",
          status: "pending",
          match_score: 96,
          driver_notes: "Existing pending offer used to test duplicate prevention.",
          submitted_at: now(),
        },
      ],
      Load: [
        {
          id: "demo-load-lockout-004",
          load_number: "HST-LOCK-004",
          status: "assigned",
          driver_id: "local-driver-user",
          origin_city: "Durham",
          origin_state: "NC",
          destination_city: "Norfolk",
          destination_state: "VA",
          equipment_type: "Sprinter",
          commodity: "Electronics",
          weight: 2100,
          miles: 190,
          rate: 950,
          total_revenue: 950,
        },
      ],
    },
  },
];

export function getPhaseRecordCount(phase) {
  return Object.values(phase.records).reduce((sum, records) => sum + records.length, 0);
}
